import {contentKinds,contentStates,validateContent,youtubeId} from './content-model.js';import {renderArticle} from './content-render.js';
export async function init({api,node,message}){
 const kind=new URLSearchParams(location.search).get('section');if(!Object.hasOwn(contentKinds,kind))return false;
 document.getElementById('heading').textContent=contentKinds[kind]+'管理';const stylesheet=node('link');stylesheet.rel='stylesheet';stylesheet.href='/content.css';document.head.append(stylesheet);
 const view=document.getElementById('manage-view'),editor=document.getElementById('editor');let page=1,status='',query='',busy=false,dirty=false,saved=null,draft=null;
 const button=(label,fn)=>{const b=node('button',label);b.type='button';b.disabled=busy;b.onclick=async()=>{try{await fn();}catch(e){message(e.message);}};return b;};
 addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
 const canLeave=()=>!busy&&(!dirty||confirm('有尚未儲存的內容，確定捨棄這些修改？'));
 function field(parent,label,value,type='text',options={}){const l=node('label',label),input=node(type==='textarea'?'textarea':type==='select'?'select':'input');if(type==='select'){for(const [v,t]of options.choices){const o=node('option',t);o.value=v;input.append(o);}}else if(type!=='textarea')input.type=type;
  if(type!=='file')input.value=value??'';for(const key of ['maxLength','required','accept'])if(options[key]!==undefined)input[key]=options[key];input.disabled=busy;l.append(input);parent.append(l);return input;}
 async function perform(fn){if(busy)return;busy=true;const controls=()=>[...editor.querySelectorAll('input,textarea,select,button'),...view.querySelectorAll('input,select,button')];controls().forEach(c=>c.disabled=true);try{await fn();}catch(e){message(e.message);}finally{busy=false;controls().forEach(c=>c.disabled=false);}}
 async function upload(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('請選擇 20 MB 以內的 JPG、PNG 或 WebP');const bitmap=await createImageBitmap(file),scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let blob;for(const quality of [.9,.75,.6,.45]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(blob&&blob.size<=1048576)break;}if(!blob||blob.size>1048576)throw Error('照片仍太大，請換一張較小的照片');const r=await fetch('/api/admin/images',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob}),d=await r.json();if(!r.ok)throw Error(d.error||'照片上傳失敗');return d.url;}
 async function open(entry){if(!canLeave())return;const d=entry?(await api('/api/admin/content-entry?id='+encodeURIComponent(entry.id))).entry:null;
  const now=new Date(),date=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');
  saved=d?structuredClone(d):null;draft=d?structuredClone(d):{id:'',version:0,kind,status:'draft',title:'',summary:'',date,cover:'',source:'',blocks:[{type:'text',text:''}]};dirty=false;drawEditor();editor.scrollIntoView({behavior:'smooth',block:'start'});message('');
 }
 function drawEditor(){editor.replaceChildren();const f=node('form');f.className='manage-form';editor.append(f);f.append(node('h2',(draft.id?'編輯':'新增')+contentKinds[kind]),node('p','草稿及封存內容不會顯示在前台。內文可交錯排列文字與照片，最多 24 個區塊、12 張照片，文字總長度最多 7500 字。'));
  const state=node('p',dirty?'有未儲存的修改':'');state.setAttribute('role','status');f.append(state);const preview=node('section');preview.className='content-draft-preview';preview.hidden=true;
  const changed=()=>{dirty=true;state.textContent='有未儲存的修改';preview.hidden=true;};
  function bound(label,key,type='text',options={}){const i=field(f,label,draft[key],type,options);i.addEventListener('input',()=>{draft[key]=i.value;changed();});return i;}
  bound('標題','title','text',{required:true,maxLength:160});bound('日期（文章／獲獎／活動／採訪日期）','date','date',{required:true});bound('列表摘要','summary','textarea',{maxLength:400});bound('來源報導／相關連結（選填，https 網址）','source','url',{maxLength:1000});bound('展示狀態','status','select',{choices:Object.entries(contentStates)});
  const cover=node('fieldset');cover.append(node('legend','封面照片'));const img=node('img');img.className='content-cover-preview';img.alt='封面照片預覽';img.hidden=!draft.cover;if(draft.cover)img.src=draft.cover;cover.append(img);
  const photo=field(cover,'上傳封面（JPG、PNG、WebP，最多 20 MB，自動縮圖）','','file',{accept:'image/jpeg,image/png,image/webp'});photo.onchange=()=>{const file=photo.files[0];if(file)perform(async()=>{draft.cover=await upload(file);img.src=draft.cover;img.hidden=false;changed();photo.value='';message('封面已上傳，請儲存內容以套用。');});};cover.append(button('移除封面',()=>{draft.cover='';img.removeAttribute('src');img.hidden=true;changed();}));f.append(cover,node('h3','內文圖文區塊'));
  const blocks=node('div');f.append(blocks);
  function drawBlocks(){blocks.replaceChildren();draft.blocks.forEach((block,index)=>{const box=node('div');box.className='content-block';box.append(node('h4',`${index+1}. ${{text:'文字段落',image:'內文照片',youtube:'YouTube 影片'}[block.type]}`));
   if(block.type==='text'){const i=field(box,'段落內容',block.text,'textarea',{maxLength:5000});i.oninput=()=>{block.text=i.value;changed();};}else if(block.type==='image'){const image=node('img');image.src=block.src;image.alt=block.caption||'內文照片';box.append(image);const caption=field(box,'圖片說明／替代文字',block.caption,'text',{maxLength:300});caption.oninput=()=>{block.caption=caption.value;image.alt=caption.value||'內文照片';changed();};}else if(block.type==='youtube'){box.append(node('p','影片： https://www.youtube.com/watch?v='+block.id));const caption=field(box,'影片說明',block.caption,'text',{maxLength:300});caption.oninput=()=>{block.caption=caption.value;changed();};}
   const actions=node('div');actions.className='form-actions';if(index)actions.append(button('上移',()=>{[draft.blocks[index-1],draft.blocks[index]]=[draft.blocks[index],draft.blocks[index-1]];changed();drawBlocks();}));if(index<draft.blocks.length-1)actions.append(button('下移',()=>{[draft.blocks[index+1],draft.blocks[index]]=[draft.blocks[index],draft.blocks[index+1]];changed();drawBlocks();}));actions.append(button('移除此區塊',()=>{draft.blocks.splice(index,1);changed();drawBlocks();}));box.append(actions);blocks.append(box);
  });}drawBlocks();
  f.append(button('＋ 新增文字段落',()=>{if(draft.blocks.length>=24)throw Error('最多 24 個區塊');draft.blocks.push({type:'text',text:''});changed();drawBlocks();}));
  const videoLink=field(f,'YouTube 嵌入程式碼或影片網址','','textarea',{maxLength:4000});f.append(node('p','貼上 YouTube 的 iframe 嵌入程式碼或分享網址，再按「加入 YouTube 影片」。影片會直接在網站內播放。'),button('＋ 加入 YouTube 影片',()=>{if(draft.blocks.length>=24)throw Error('最多 24 個區塊');const id=youtubeId(videoLink.value.trim());draft.blocks.push({type:'youtube',id,caption:''});videoLink.value='';changed();drawBlocks();}));
  const photos=field(f,'＋ 加入內文照片（可多選；JPG、PNG、WebP）','','file',{accept:'image/jpeg,image/png,image/webp'});photos.multiple=true;photos.onchange=()=>{const files=[...photos.files];if(!files.length)return;perform(async()=>{if(draft.blocks.length+files.length>24||draft.blocks.filter(b=>b.type==='image').length+files.length>12)throw Error('最多 24 個區塊及 12 張內文照片');for(const file of files){const src=await upload(file);draft.blocks.push({type:'image',src,caption:''});changed();drawBlocks();}photos.value='';message('照片已加入，請填寫圖片說明並儲存內容。');});};
  const controls=node('div');controls.className='form-actions content-editor-actions';const save=node('button','儲存內容');save.type='submit';controls.append(save,button('預覽圖文',()=>{const value=validateContent({...draft,status:'draft'});preview.replaceChildren(node('h2','草稿預覽（尚未儲存）'));const article=node('article');renderArticle(article,value);preview.append(article);preview.hidden=false;preview.scrollIntoView({behavior:'smooth'});}),button('關閉編輯',()=>{if(canLeave()){dirty=false;editor.replaceChildren();}}));if(saved)controls.append(button('還原至上次儲存',()=>{draft=structuredClone(saved);dirty=false;drawEditor();message('已還原至上次儲存的內容。');}));f.append(controls,preview);
  f.onsubmit=e=>{e.preventDefault();perform(async()=>{validateContent(draft);const result=await api('/api/admin/content-entry','POST',draft);saved=structuredClone(result.entry);draft=structuredClone(saved);dirty=false;drawEditor();await load();message(draft.status==='published'?'已發布，前台現在可以看到這篇內容。':draft.status==='archived'?'已封存，前台不再顯示，仍可在後台恢復。':'草稿已儲存，尚未在前台顯示。');});};
 }
 async function load(){view.replaceChildren();const toolbar=node('div');toolbar.className='form-actions';toolbar.append(button('＋ 新增'+contentKinds[kind],()=>open()));const link=node('a','查看前台'+contentKinds[kind]);link.href='/content.html?kind='+kind;link.target='_blank';link.rel='noopener';toolbar.append(link);view.append(toolbar);
  const search=node('form');search.className='search-form';const q=field(search,'搜尋標題',query,'search',{maxLength:100}),filter=field(search,'狀態篩選',status,'select',{choices:[['','全部狀態'],...Object.entries(contentStates)]}),submit=node('button','搜尋／篩選');search.append(submit);search.onsubmit=e=>{e.preventDefault();page=1;query=q.value;status=filter.value;load().catch(e=>message(e.message));};view.append(search);
  const data=await api('/api/admin/content?'+new URLSearchParams({kind,page,status,q:query}));if(!data.entries.length)view.append(node('p','目前沒有符合條件的內容，按上方按鈕即可新增。'));
  else{const wrap=node('div');wrap.className='table-wrap';const table=node('table'),head=node('thead'),tr=node('tr');for(const title of ['日期','標題','狀態','操作'])tr.append(node('th',title));head.append(tr);const body=node('tbody');for(const entry of data.entries){const row=node('tr');row.append(node('td',entry.date),node('td',entry.title),node('td',contentStates[entry.status]));const cell=node('td');cell.append(button('編輯',()=>open(entry)));if(entry.status==='published'){const a=node('a','查看文章');a.href='/article.html?id='+encodeURIComponent(entry.id);a.target='_blank';a.rel='noopener';cell.append(' ',a);}row.append(cell);body.append(row);}table.append(head,body);wrap.append(table);view.append(wrap);}
  const pages=node('div');pages.className='toolbar';if(page>1)pages.append(button('上一頁',()=>{page--;return load();}));pages.append(node('span','第 '+data.page+' 頁'));if(data.hasMore)pages.append(button('下一頁',()=>{page++;return load();}));view.append(pages);
 }
 await load();message('');return true;
}
