import {showMember,newMember} from './admin-member-detail.js';
export async function init({api,node,message}){
 if(await (await import('./admin-content.js')).init({api,node,message}))return;
 if(await (await import('./admin-homepage.js')).init({api,node,message}))return;
 if(await (await import('./admin-modules.js')).init({api,node,message}))return;
 const $=id=>document.getElementById(id),view=$('manage-view'),editor=$('editor'),section=new URLSearchParams(location.search).get('section')||'products';let page=1,query='',busy=false;
 const titles={products:'商品管理',stock:'庫存管理',members:'會員管理',audit:'操作紀錄'};$('heading').textContent=titles[section]||'商品管理';
 const button=(text,fn,cls='')=>{const b=node('button',text);b.type='button';b.className=cls;b.onclick=fn;return b;};
 function field(form,label,value='',type='text'){const wrap=node('div'),id='f-'+crypto.randomUUID(),l=node('label',label);l.htmlFor=id;const input=node(type==='textarea'?'textarea':'input');input.id=id;if(type!=='textarea')input.type=type;input.value=value??'';wrap.append(l,input);form.append(wrap);return input;}
 function select(form,label,value,choices){const l=node('label',label),input=node('select');for(const [key,text] of choices){const option=node('option',text);option.value=key;input.append(option);}input.value=value;l.append(input);form.append(l);return input;}
 async function action(form,fn){if(busy)return;busy=true;const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
 function form(title){editor.replaceChildren();const f=node('form');f.className='manage-form';f.append(node('h2',title));editor.append(f);f.scrollIntoView({behavior:'smooth',block:'start'});return f;}
 function table(headers,data,render){const wrap=node('div');wrap.className='table-wrap';const t=node('table'),head=node('thead'),tr=node('tr');headers.forEach(h=>tr.append(node('th',h)));head.append(tr);const body=node('tbody');for(const row of data){const tr=node('tr');for(const content of render(row)){const td=node('td');typeof content==='object'?td.append(content):td.textContent=content??'';tr.append(td);}body.append(tr);}t.append(head,body);wrap.append(t);view.append(wrap);}
 async function product(p={sku:'item-'+crypto.randomUUID().slice(0,12),family:'',name:'',variant:'標準',price:1,category:'pen',description:'',active:0,images:[],version:0}){
  const f=form(p.version?'編輯商品／規格':'新增商品／規格'),grid=node('div');grid.className='form-grid';f.append(grid);
  const sku=field(grid,'商品代碼（建立後固定）',p.sku);sku.readOnly=!!p.version;sku.required=true;
  const name=field(grid,'商品名稱',p.name);name.required=true;name.maxLength=200;
  const nibs=(await api('/api/admin/nibs')).nibs.filter(n=>n.active||n.name===p.variant);let variant=p.category==='pen'?select(grid,'可搭配尖型',p.variant,nibs.map(n=>[n.name,n.name+(n.active?'':'（停用）')])):field(grid,'規格',p.variant);variant.required=true;variant.maxLength=100;
  const price=field(grid,'售價（新台幣整數）',p.price,'number');price.min=1;price.max=10000000;price.required=true;
  const categories=(await api('/api/admin/categories')).categories;
  const choices=categories.filter(c=>c.parent).map(c=>[c.id,(categories.find(b=>b.id===c.parent)?.name||'')+'／'+c.name]);
  const category=select(grid,'商品分類',p.category_id||p.category,[['pen','未歸類／手工鋼筆'],['ink','未歸類／手工墨水'],['craft','未歸類／其他商品'],...choices]);
  const kind=()=>categories.find(c=>c.id===category.value)?.kind||category.value;
  category.onchange=()=>{const old=variant.parentElement;const holder=node('div');old.replaceWith(holder);variant=kind()==='pen'?select(holder,'可搭配尖型','',nibs.filter(n=>n.active).map(n=>[n.name,n.name])):field(holder,'規格','標準');variant.required=true;};
  const active=select(grid,'販售狀態',String(p.active),[['0','下架／草稿'],['1','上架']]);
  const description=field(f,'商品介紹',p.description,'textarea');description.maxLength=8000;
  let images=[...p.images];const photos=node('div');photos.className='photos';f.append(node('h3','商品照片（最多六張，第一張為主照片）'),photos);
  function draw(){photos.replaceChildren();images.forEach((src,i)=>{const box=node('div');box.className='photo-card';box.draggable=true;box.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));box.ondragover=e=>e.preventDefault();box.ondrop=e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(from)&&from>=0&&from<images.length){images.splice(i,0,images.splice(from,1)[0]);draw();}};const img=node('img');img.src=src;img.alt='商品照片 '+(i+1);box.append(img,button('移除',()=>{images.splice(i,1);draw();}));if(i)box.append(button('向前移',()=>{[images[i-1],images[i]]=[images[i],images[i-1]];draw();}),button('設為主照片',()=>{images.unshift(images.splice(i,1)[0]);draw();}));photos.append(box);});}draw();
  const upload=field(f,'上傳 JPG、PNG 或 WebP（自動縮圖）','','file');upload.accept='image/jpeg,image/png,image/webp';upload.multiple=true;
  upload.onchange=()=>action(f,async()=>{const files=[...upload.files];if(images.length+files.length>6)throw Error('最多六張照片，請先移除不需要的照片');for(const file of files){if(file.size>20*1024*1024)throw Error('原始照片請小於 20 MB');const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let blob;for(const quality of [.88,.72,.55]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(blob&&blob.size<=1048576)break;}if(!blob||blob.size>1048576)throw Error('照片仍太大，請換一張較小的照片');const r=await fetch('/api/admin/images',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});const d=await r.json();if(!r.ok)throw Error(d.error||'照片上傳失敗');images.push(d.url);draw();}upload.value='';message('照片已上傳，請儲存商品以套用。');});
  const actions=node('div');actions.className='form-actions';const save=node('button','儲存商品');save.type='submit';actions.append(save,button('關閉',()=>editor.replaceChildren()));actions.append(button('草稿預覽',()=>{const panel=node('section');panel.className='manage-form draft-preview';panel.append(node('h2','草稿預覽（尚未發布）'),node('h3',name.value),node('p',variant.value+' · NT$ '+price.value));const desc=node('p',description.value);desc.style.whiteSpace='pre-wrap';panel.append(desc);api('/api/admin/families').then(d=>{const video=d.families.find(x=>x.family===p.family)?.video;if(video){const frame=node('iframe');frame.src='https://www.youtube-nocookie.com/embed/'+video;frame.title='商品影片';frame.style.cssText='width:100%;aspect-ratio:16/9;border:0';panel.append(frame);}}).catch(e=>message(e.message));for(const src of images){const img=node('img');img.src=src;img.alt=name.value;img.style.maxWidth='100%';panel.append(img);}panel.append(button('關閉預覽',()=>panel.remove()));f.append(panel);panel.scrollIntoView({behavior:'smooth'});}));if(p.version){actions.append(button('複製整個商品為草稿',()=>action(f,async()=>{await api('/api/admin/copy-product','POST',{family:p.family});editor.replaceChildren();await load();message('整個商品及尖型已複製為草稿，庫存為零。');})));actions.append(button('新增同商品規格',()=>product({...p,sku:'item-'+crypto.randomUUID().slice(0,12),version:0,active:0,variant:''})));if(p.active)actions.append(button('下架封存',()=>action(f,async()=>{await api('/api/admin/product','POST',{...p,active:0});editor.replaceChildren();await load();message('商品已下架封存，既有訂單與紀錄保留。');}),'danger'));}f.append(actions);
  f.onsubmit=e=>{e.preventDefault();action(f,async()=>{await api('/api/admin/product','POST',{sku:sku.value,family:p.family||sku.value,name:name.value,variant:variant.value,price:Number(price.value),category:kind(),category_id:categories.some(c=>c.id===category.value)?category.value:'',active:Number(active.value),description:description.value,images,version:p.version});editor.replaceChildren();await load();message('商品已儲存。新商品庫存為零，請到庫存管理入庫。');});};
 }
 function stock(p){const f=form(p.name+'／'+p.variant);f.append(node('p',`目前可售 ${p.available} 件；累計售出 ${p.sold} 件。已被訂單保留的數量不包含在可售庫存。`));const delta=field(f,'增減數量（入庫填正數，盤損填負數）','','number');delta.min=-100000;delta.max=100000;delta.required=true;const reason=field(f,'異動原因','','textarea');reason.required=true;reason.maxLength=500;const save=node('button','確認庫存異動');save.type='submit';f.append(save);f.onsubmit=e=>{e.preventDefault();action(f,async()=>{await api('/api/admin/stock','POST',{sku:p.sku,expected:p.available,delta:Number(delta.value),reason:reason.value});editor.replaceChildren();await load();message('庫存已更新並記錄異動原因。');});};}
 async function member(m){return showMember({api,node,message,editor,m,onStatusSaved:async()=>{editor.replaceChildren();await load();}});}
 async function load(){message('正在讀取…');view.replaceChildren();const search=node('form');search.className='search-form';const input=node('input');input.placeholder=section==='members'?'搜尋姓名或信箱':'搜尋商品名稱或代碼';input.value=query;input.maxLength=100;const submit=node('button','搜尋');submit.type='submit';if(section!=='audit'){search.append(input,submit);search.onsubmit=e=>{e.preventDefault();query=input.value;page=1;load().catch(e=>message(e.message));};view.append(search);}if(section==='members')view.append(button('＋ 手動新增會員',()=>newMember({api,node,message,editor,onStatusSaved:async()=>{await load();}})));if(section==='products')view.append(button('＋ 新增商品',()=>product()));
  const endpoint=section==='members'?'members':section==='audit'?'audit':'products';const d=await api('/api/admin/'+endpoint+'?'+new URLSearchParams({q:query,page}));
  if(endpoint==='products')table(['商品／規格','代碼','售價','狀態','可售','已售','操作'],d.products,p=>[p.name+'\n'+p.variant,p.sku,'NT$ '+p.price.toLocaleString(),p.active?'上架':'下架',p.available,p.sold,button(section==='stock'?'調整庫存':'編輯',()=>section==='stock'?stock(p):product(p))]);
  else if(endpoint==='members')table(['姓名','信箱','國家','狀態','購買紀錄','操作'],d.members,m=>[button(m.name,()=>member(m).catch(e=>message(e.message)),'member-name'),m.email,m.country,m.offline?'手動建檔':m.active?'啟用':'停用','網站 '+m.order_count+'／手動 '+m.manual_count,button('查看／管理',()=>member(m).catch(e=>message(e.message)))]);
  else table(['時間','操作','對象','異動前 → 後','原因'],d.records,r=>[new Date(r.created_at).toLocaleString('zh-TW'),({'coupon.first-code':'首購專用券新增／修改','coupon.first-purchase':'首購優惠券設定','member.create':'手動新增會員','member.profile':'基本資料／購買紀錄','member.service':'會員編號／保固','content.create':'新增內容','content.update':'更新內容','homepage.update':'首頁編輯','product.create':'新增商品','product.update':'編輯商品','stock.adjust':'庫存異動','member.status':'會員狀態','order.notes':'訂單備註'})[r.action]||r.action,r.target,r.before_value+' → '+r.after_value,r.reason]);
  const nav=node('div');nav.className='toolbar';const prev=button('上一頁',()=>{page--;load().catch(e=>message(e.message));}),next=button('下一頁',()=>{page++;load().catch(e=>message(e.message));});prev.disabled=page===1;next.disabled=!d.hasMore;nav.append(prev,node('span','第 '+page+' 頁'),next);view.append(nav);message('');
 }await load();
}
