import {createLogistics,logisticsMac,logisticsNotify,printLogistics,queryLogistics,createFields} from './logistics.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {checkMac} from './ecpay.js';
import {shippingQuote,shippingStatements,shippingSchema} from './shipping.js';
import {firstGiftQuote,firstGiftStatements,firstGiftForOrder} from './first-purchase.js';
const require=createRequire(import.meta.url);
const {Miniflare,convertV4MiniflareOptions}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler')]}));
test('live bank checkout, buyer report, administrator settlement and shipment notifications',async()=>{
 const mf=new Miniflare(convertV4MiniflareOptions({modules:[{type:'ESModule',path:fileURLToPath(new URL('./worker.js',import.meta.url)),contents:readFileSync(new URL('./worker.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./first-purchase.js',import.meta.url)),contents:readFileSync(new URL('./first-purchase.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./countries.js',import.meta.url)),contents:readFileSync(new URL('./countries.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./ecpay.js',import.meta.url)),contents:readFileSync(new URL('./ecpay.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./payments.js',import.meta.url)),contents:readFileSync(new URL('./payments.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./inventory.js',import.meta.url)),contents:readFileSync(new URL('./inventory.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./commerce.js',import.meta.url)),contents:readFileSync(new URL('./commerce.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./modules.js',import.meta.url)),contents:readFileSync(new URL('./modules.js',import.meta.url),'utf8')},...['logistics.js','live-payments.js','newsletter-store.js','newsletter-model.js','nib-guide-store.js','nib-guide-model.js','product-translations.js','order-notifications.js','manual-invoice.js','shipping.js','homepage-store.js','homepage-social.js','homepage-config.js','content-store.js','content-model.js'].map(f=>({type:'ESModule',path:fileURLToPath(new URL(f,import.meta.url)),contents:readFileSync(new URL(f,import.meta.url),'utf8')}))],compatibilityDate:'2026-09-07',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{APP_ENV:'staging',PAYMENTS_LIVE:'true',ECPAY_MERCHANT_ID:'3442057',MAIL_FROM:'shop@example.test',MAIL_ORIGIN:'https://shop.test',PAYMENT_ORIGIN:'https://wugong-test.wugong-pen.workers.dev',BANK_CONFIG:JSON.stringify({bank:'Bank',code:'009',branch:'Branch',holder:'Holder',account:'123456789',days:3})}}));
 try{
  const db=await mf.getD1Database('DB');
  const schema=readFileSync(new URL('./schema-members.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'');
  for(const statement of schema.split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-admin.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  const response=await mf.dispatchFetch('https://shop.test/api/member/register',{method:'POST',headers:{Origin:'https://shop.test','Content-Type':'application/json'},body:JSON.stringify({email:'runtime@example.test',password:'runtime test password is long',name:'測試會員',birthday:'1990-01-01',country:'TW'})});
  assert.equal(response.status,200,await response.clone().text());const result=await response.json();assert.equal(response.status,200,JSON.stringify(result));assert.equal(result.member.name,'測試會員');
  const cookie=response.headers.get('set-cookie').split(';')[0];
  const me=await mf.dispatchFetch('https://shop.test/api/member',{headers:{Cookie:cookie}});assert.equal((await me.json()).member.email,'runtime@example.test');
  assert.equal((await mf.dispatchFetch('https://shop.test/api/admin/session',{headers:{Cookie:cookie}})).status,403);
  await db.prepare('INSERT INTO admin_members VALUES (?,1,?)').bind(result.member.id,new Date().toISOString()).run();
  const adminLogin=await mf.dispatchFetch('https://shop.test/api/admin/login',{method:'POST',headers:{Origin:'https://shop.test','Content-Type':'application/json'},body:JSON.stringify({email:'runtime@example.test',password:'runtime test password is long'})});
  assert.equal(adminLogin.status,200);const adminCookie=adminLogin.headers.get('set-cookie').split(';')[0];
  assert.equal((await mf.dispatchFetch('https://shop.test/api/admin/session',{headers:{Cookie:adminCookie}})).status,200);
  await db.prepare('CREATE TABLE orders(order_number TEXT PRIMARY KEY,customer_name TEXT,phone TEXT,email TEXT,address TEXT,shipping TEXT,payment TEXT,note TEXT,items TEXT,total INTEGER,status TEXT,created_at TEXT)').run();
  for(const statement of readFileSync(new URL('./schema-payments.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-checkout.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').match(/CREATE TRIGGER[\s\S]*?\nEND;|CREATE (?:TABLE|INDEX)[\s\S]*?;/g))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./seed-inventory-staging.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-commerce.sql',import.meta.url),'utf8').match(/CREATE TRIGGER[\s\S]*?END;|CREATE (?:TABLE|INDEX)[\s\S]*?;/g))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./seed-products.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-modules.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await db.prepare(statement).run();for(const statement of readFileSync(new URL('./schema-categories-gifts.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await db.prepare(statement).run();await db.prepare('UPDATE product_families SET confirmed=1').run();await db.prepare("UPDATE inventory SET available=5 WHERE sku LIKE 'body-%'").run();

 const headers={Origin:'https://shop.test','Content-Type':'application/json',Cookie:cookie},adminHeaders={...headers,Cookie:adminCookie};
 const map=await mf.dispatchFetch('https://shop.test/api/cvs/start',{method:'POST',headers,body:JSON.stringify({subtype:'FAMIC2C'})});assert.equal(map.status,200);const mapData=await map.json();assert.equal(mapData.fields.IsCollection,'N');assert.equal(mapData.action,'https://logistics.ecpay.com.tw/Express/map');
 const mapFields={...mapData.fields,CVSStoreID:'123456',CVSStoreName:'門市',CVSAddress:'高雄市鳳山區示例路1號'};
 const callback=()=>mf.dispatchFetch('https://shop.test/cvs/return',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(mapFields),redirect:'manual'});
 assert.equal((await callback()).status,303);assert.equal((await callback()).status,409);
 const storeResult=await mf.dispatchFetch('https://shop.test/api/cvs/selection?token='+mapData.fields.ExtraData,{headers});assert.equal(storeResult.status,200);assert.equal((await storeResult.json()).store.storeId,'123456');
 assert.equal((await mf.dispatchFetch('https://shop.test/api/cvs/selection?token='+mapData.fields.ExtraData)).status,401);

 const post=(path,data,h=headers)=>mf.dispatchFetch('https://shop.test'+path,{method:'POST',headers:h,body:JSON.stringify(data)});
 const checkout={customer:{name:'Buyer',phone:'0900000000',address:'Address',country:'TW'},items:[{id:'pojun-單尖',nib:'單尖',quantity:1}],expectedTotal:25000,payment:'bank',shipping:'cvs',storeToken:mapData.fields.ExtraData};
 const overLimit=await post('/api/order',checkout,{...headers,'Idempotency-Key':'over-limit-fixture-0001'});assert.equal(overLimit.status,400);assert.match((await overLimit.json()).error,/20,000/);
 await db.prepare("UPDATE products SET price=15000 WHERE sku='pojun-單尖'").run();checkout.expectedTotal=15000;
 const placed=await post('/api/order',checkout,{...headers,'Idempotency-Key':'live-order-fixture-0001'});assert.equal(placed.status,200,await placed.clone().text());const {orderNumber}=await placed.json();
 const savedStore=await db.prepare('SELECT address,shipping FROM orders WHERE order_number=?').bind(orderNumber).first();assert.match(savedStore.address,/123456/);assert.match(savedStore.shipping,/全家/);assert.equal((await mf.dispatchFetch('https://shop.test/api/cvs/selection?token='+mapData.fields.ExtraData,{headers})).status,400);
 const attempt=await db.prepare('SELECT * FROM payment_attempts WHERE order_number=?').bind(orderNumber).first();assert.equal(JSON.parse(attempt.bank_details).account,'123456789');
 let notices=(await db.prepare('SELECT payload FROM order_notifications').all()).results;assert.equal(notices.length,2);assert.ok(notices.every(n=>JSON.parse(n.payload).text.includes('123456')));assert.ok(notices.some(n=>JSON.parse(n.payload).text.includes('123456789')));
 const report={orderNumber,last5:'54321',date:new Date(Date.now()+8*3600000).toISOString().slice(0,10)};
 const reported=await post('/api/payments/bank/report',report);assert.equal(reported.status,200,await reported.clone().text());
 const again=await post('/api/payments/bank/report',report);assert.equal(again.status,200);
 assert.equal((await db.prepare('SELECT status FROM orders WHERE order_number=?').bind(orderNumber).first()).status,'pending');
 const proof={orderNumber,reference:'BANK-REF-001',amount:15000,confirmed:true};
 assert.equal((await post('/api/admin/bank/confirm',proof)).status,403);
 const badOrigin=await post('/api/admin/bank/confirm',proof,{...adminHeaders,Origin:'https://evil.test'});assert.equal(badOrigin.status,403);
 const paid=await post('/api/admin/bank/confirm',proof,adminHeaders);assert.equal(paid.status,200,await paid.clone().text());
 assert.equal((await post('/api/admin/bank/confirm',proof,adminHeaders)).status,409);
 const logEnv={DB:db,PAYMENTS_LIVE:'true',ECPAY_MERCHANT_ID:'3442057',ECPAY_LOGISTICS_HASH_KEY:'fixture-key-only',ECPAY_LOGISTICS_HASH_IV:'fixture-iv-only',PAYMENT_ORIGIN:'https://shop.test'};
 const logAdmin={id:result.member.id};
 assert.equal((await mf.dispatchFetch('https://shop.test/api/admin/logistics',{headers})).status,403);
 assert.equal((await post('/api/admin/logistics',{action:'settings',sender_name:'寄件者',sender_phone:'0900000000',version:0},{...adminHeaders,Origin:'https://evil.test'})).status,403);
 const setting=await post('/api/admin/logistics',{action:'settings',sender_name:'寄件者',sender_phone:'0900000000',version:0},adminHeaders);assert.equal(setting.status,200,await setting.clone().text());
 const paidOrder=await db.prepare('SELECT * FROM orders WHERE order_number=?').bind(orderNumber).first();await assert.rejects(Promise.resolve().then(()=>createFields(logEnv,paidOrder,{subtype:'FAMIC2C',store_id:'123456'},{sender_name:'寄件者',sender_phone:'0900000000'},25000,'test')),/20,000/);
 // Isolated fixture value: verify successful pure-pickup creation without any external call.
 await db.prepare('UPDATE orders SET total=15000 WHERE order_number=?').bind(orderNumber).run();
 await db.prepare('UPDATE payment_receipts SET amount=15000 WHERE order_number=?').bind(orderNumber).run();
 const orderBefore=await db.prepare('SELECT * FROM orders WHERE order_number=?').bind(orderNumber).first();
 await assert.rejects(Promise.resolve().then(()=>createFields(logEnv,{...orderBefore,customer_name:'x'},{subtype:'FAMIC2C',store_id:'123456'},{sender_name:'寄件者',sender_phone:'0900000000'},15000,'test')),/收件姓名/);
 let calls=0,notice;
 const send=async(url,options)=>{calls++;assert.equal(url,'https://logistics.ecpay.com.tw/Express/Create');const f=Object.fromEntries(new URLSearchParams(options.body));assert.equal(f.IsCollection,'N');assert.equal(f.ReceiverStoreID,'123456');assert.equal(f.GoodsAmount,'15000');assert.equal(f.CheckMacValue,logisticsMac(f,logEnv.ECPAY_LOGISTICS_HASH_KEY,logEnv.ECPAY_LOGISTICS_HASH_IV));notice={MerchantID:f.MerchantID,MerchantTradeNo:f.MerchantTradeNo,AllPayLogisticsID:'123456789',LogisticsType:'CVS',LogisticsSubType:'FAMIC2C',GoodsAmount:'15000',RtnCode:'300',RtnMsg:'Created',UpdateStatusDate:'2026/10/05 10:00:00',CVSPaymentNo:'123456789012',CVSValidationNo:''};notice.CheckMacValue=logisticsMac(notice,logEnv.ECPAY_LOGISTICS_HASH_KEY,logEnv.ECPAY_LOGISTICS_HASH_IV);return new Response('1|'+new URLSearchParams(notice));};
 const built=await createLogistics(logEnv,logAdmin,orderNumber,send);assert.equal(built.state,'created');assert.equal(built.fields,undefined);
 await createLogistics(logEnv,logAdmin,orderNumber,send);assert.equal(calls,1);
 assert.equal((await db.prepare('SELECT status FROM orders WHERE order_number=?').bind(orderNumber).first()).status,'paid');
 assert.equal((await db.prepare('SELECT tracking FROM order_management WHERE order_number=?').bind(orderNumber).first()).tracking,'123456789012');
 const print=await printLogistics(logEnv,orderNumber);assert.equal(print.action,'https://logistics.ecpay.com.tw/Express/PrintFAMIC2COrderInfo');assert.equal(print.fields.CVSPaymentNo,'123456789012');
 const badNotice=new Request('https://shop.test/logistics/notify',{method:'POST',body:new URLSearchParams({...notice,GoodsAmount:'1'})});assert.equal((await logisticsNotify(badNotice,logEnv)).status,400);
 const sendNotice=async n=>{n.CheckMacValue=logisticsMac(n,logEnv.ECPAY_LOGISTICS_HASH_KEY,logEnv.ECPAY_LOGISTICS_HASH_IV);return logisticsNotify(new Request('https://shop.test/logistics/notify',{method:'POST',body:new URLSearchParams(n)}),logEnv);};
 assert.equal(await(await sendNotice({...notice,RtnCode:'3018',RtnMsg:'Arrived',UpdateStatusDate:'2026/10/06 10:00:00'})).text(),'1|OK');
 await sendNotice(notice);assert.equal((await db.prepare('SELECT status_code FROM logistics_orders WHERE order_number=?').bind(orderNumber).first()).status_code,'3018');
 await assert.rejects(queryLogistics(logEnv,orderNumber,async()=>new Response('MerchantID=3442057&CheckMacValue=BAD')),/驗證/);
 // Simulate a lost create reply: the durable row prevents a second purchase of logistics.
 await db.prepare("UPDATE logistics_orders SET state='uncertain',logistics_id=NULL WHERE order_number=?").bind(orderNumber).run();
 await assert.rejects(createLogistics(logEnv,logAdmin,orderNumber,send),/勿重複建立/);assert.equal(calls,1);
 await queryLogistics(logEnv,orderNumber,async()=>{const q={...notice,LogisticsType:'CVS_FAMIC2C',LogisticsStatus:'3018'};delete q.LogisticsSubType;delete q.UpdateStatusDate;q.CheckMacValue=logisticsMac(q,logEnv.ECPAY_LOGISTICS_HASH_KEY,logEnv.ECPAY_LOGISTICS_HASH_IV);return new Response(new URLSearchParams(q));});
 assert.equal((await db.prepare('SELECT state FROM logistics_orders WHERE order_number=?').bind(orderNumber).first()).state,'created');
 await db.prepare("UPDATE products SET price=25000 WHERE sku='pojun-單尖'").run();
 const manualCheckout={...checkout,expectedTotal:25000,shipping:'cvs_manual',storeToken:null,manualStore:{name:'人工買家',phone:'0900000001',brand:'UNIMARTC2C',storeName:'台北市 示範門市'}};
 const manualResponse=await post('/api/order',manualCheckout,{...headers,'Idempotency-Key':'manual-cvs-fixture-0001'});assert.equal(manualResponse.status,200,await manualResponse.clone().text());const manualNumber=(await manualResponse.json()).orderNumber;
 const manualOrder=await db.prepare('SELECT * FROM orders WHERE order_number=?').bind(manualNumber).first();assert.match(manualOrder.shipping,/人工寄出/);assert.match(manualOrder.address,/示範門市/);assert.equal(manualOrder.customer_name,'人工買家');assert.equal(manualOrder.phone,'0900000001');
 const manualNotice=JSON.parse((await db.prepare('SELECT payload FROM order_notifications WHERE id=?').bind('new-order/'+manualNumber).first()).payload);assert.match(manualNotice.text,/人工寄出/);
 assert.equal(await db.prepare('SELECT used_order FROM cvs_selections WHERE used_order=?').bind(manualNumber).first(),null);

 const ship=await post('/api/admin/order/status',{orderNumber,expectedStatus:'paid',status:'shipped',factoryDate:new Date(Date.now()+8*3600000).toISOString().slice(0,10)},adminHeaders);assert.equal(ship.status,200,await ship.clone().text());
 const rows=(await db.prepare('SELECT id,payload FROM order_notifications WHERE id LIKE ?').bind('%'+orderNumber+'%').all()).results;
 for(const prefix of ['new-order/','buyer-confirmed/','bank-report/','buyer-paid/','buyer-shipped/','buyer-care/'])assert.equal(rows.filter(n=>n.id.startsWith(prefix)).length,1,prefix);
 assert.match(JSON.parse(rows.find(n=>n.id.startsWith('buyer-shipped/')).payload).text,/Factory date/);
 assert.equal((await db.prepare('SELECT status FROM orders WHERE order_number=?').bind(orderNumber).first()).status,'shipped');
 }finally{await mf.dispose();}
});
