import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './worker.js';
function database(){
 const sql=new DatabaseSync(':memory:');
 sql.exec('CREATE TABLE orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_number TEXT UNIQUE,customer_name TEXT,phone TEXT,email TEXT,address TEXT,shipping TEXT,payment TEXT,note TEXT,items TEXT,total REAL,status TEXT,created_at TEXT);');
 sql.exec(readFileSync(new URL('./schema-members.sql',import.meta.url),'utf8'));
 for(const file of ['schema-payments.sql','schema-checkout.sql','seed-inventory-staging.sql'])sql.exec(readFileSync(new URL('./'+file,import.meta.url),'utf8'));
 const prepare=(query)=>{let params=[];return{bind(...values){params=values;return this;},async first(){return sql.prepare(query).get(...params)||null;},async all(){return {results:sql.prepare(query).all(...params)};},async run(){const result=sql.prepare(query).run(...params);return{meta:{changes:result.changes}};}};};
 return{sql,prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
}
test('member lifecycle, owner-only orders, validation and session revocation',async()=>{
 const DB=database(),env={DB,APP_ENV:'staging',BANK_TEST_CONFIG:JSON.stringify({bank:'test',code:'test',branch:'test',holder:'test',account:'test',days:3}),ASSETS:{fetch:async()=>new Response('asset')}};
 const call=async(path,method='GET',data,token='',extra={})=>{
  const response=await worker.fetch(new Request('https://shop.test'+path,{method,headers:{Origin:'https://shop.test','Content-Type':'application/json',Cookie:token,...extra},body:data===undefined?undefined:JSON.stringify(data)}),env);
  return{status:response.status,headers:response.headers,data:response.headers.get('Content-Type')?.includes('json')?await response.json():await response.text()};
 };
 const registration={email:'member-a@example.test',password:'a long safe test password',name:'測試甲',birthday:'1990-03-01',country:'TW'};
 assert.equal((await call('/api/order','POST',{})).status,401);
 assert.equal((await call('/checkout.html')).status,303);
 assert.equal((await call('/api/member/register','POST',{...registration,birthday:'2025-02-30'})).status,400);
 assert.equal((await call('/api/member/register','POST',{...registration,country:'ZZ'})).status,400);
 const a=await call('/api/member/register','POST',registration);assert.equal(a.status,200,JSON.stringify(a.data));
 const tokenA=a.headers.get('set-cookie').split(';')[0];
 assert.match(a.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Lax/);
 assert.ok(!JSON.stringify(a.data).includes('password_hash'));
 assert.notEqual(DB.sql.prepare('SELECT password_hash FROM members').get().password_hash,registration.password);
 assert.equal((await call('/api/member/register','POST',{...registration,email:registration.email.toUpperCase()})).status,409);
 assert.equal((await call('/api/member/login','POST',{email:registration.email,password:'incorrect'})).status,401);
 assert.equal((await call('/api/member','PATCH',{...registration,name:'新的姓名'},tokenA,{Origin:'https://evil.test'})).status,403);
 assert.equal((await call('/api/member','PATCH',{...registration,name:'新的姓名',phone:'0900000000',address:'測試地址'},tokenA)).status,200);
 assert.equal((await call('/api/member','GET',undefined,tokenA)).data.member.name,'新的姓名');
 const b=await call('/api/member/register','POST',{...registration,email:'member-b@example.test',name:'測試乙'});const tokenB=b.headers.get('set-cookie').split(';')[0];
 const order={customer:{name:'測試收件人',phone:'0000000000',address:'測試地址',country:'TW',email:'spoof@example.test'},items:[{id:'product-fuji',product:'測試鋼筆',nib:'WUGONG 筆尖',price:100,quantity:2}],shipping:'宅配',payment:'bank',expectedTotal:240000,total:1,memberId:b.data.member.id};
 const submitted=await call('/api/order','POST',order,tokenA,{'Idempotency-Key':'test-order-00000001'});assert.equal(submitted.status,200,JSON.stringify(submitted.data));
 const duplicate=await call('/api/order','POST',order,tokenA,{'Idempotency-Key':'test-order-00000001'});assert.equal(duplicate.data.orderNumber,submitted.data.orderNumber);
 assert.equal(DB.sql.prepare('SELECT count(*) n FROM orders').get().n,1);
 const mine=await call('/api/member/orders','GET',undefined,tokenA);assert.equal(mine.data.orders.length,1);assert.equal(mine.data.orders[0].email,registration.email);assert.equal(mine.data.orders[0].total,240000);
 assert.equal((await call('/api/member/orders','GET',undefined,tokenB)).data.orders.length,0);
 assert.equal((await call('/api/member/orders/'+submitted.data.orderNumber,'GET',undefined,tokenB)).status,404);
 assert.equal((await call('/api/orders','GET',undefined,tokenA)).status,403);
 assert.equal((await call('/api/order/status','POST',{status:'paid'},tokenA)).status,403);
 await call('/api/member/logout','POST',{},tokenB);assert.equal((await call('/api/member/orders','GET',undefined,tokenB)).status,401);
 const login=await call('/api/member/login','POST',{email:registration.email,password:registration.password});const second=login.headers.get('set-cookie').split(';')[0];
 assert.equal((await call('/api/member/password','POST',{currentPassword:registration.password,password:'a new long safe password'},tokenA)).status,200);
 assert.equal((await call('/api/member/orders','GET',undefined,tokenA)).status,401);
 assert.equal((await call('/api/member/orders','GET',undefined,second)).status,401);
 const changed=await call('/api/member/login','POST',{email:registration.email,password:'a new long safe password'});assert.equal(changed.status,200);
 const expired=changed.headers.get('set-cookie').split(';')[0];DB.sql.exec('UPDATE member_sessions SET expires_at=0');assert.equal((await call('/api/member/orders','GET',undefined,expired)).status,401);
 for(let i=0;i<10;i++)await call('/api/member/login','POST',{email:'nobody@example.test',password:'wrong'});
 assert.equal((await call('/api/member/login','POST',{email:'nobody@example.test',password:'wrong'})).status,429);
 assert.equal((await call('/api/member/register','POST',registration,'',{Origin:'https://evil.test'})).status,403);
 DB.sql.exec(readFileSync(new URL('./schema-members.sql',import.meta.url),'utf8'));
 assert.equal(DB.sql.prepare('SELECT count(*) n FROM orders').get().n,1);
});


test('email verification and password reset: one-use, expiry, isolation and revocation',async t=>{
 const DB=database(),mail=[];
 const env={DB,APP_ENV:'staging',RESEND_API_KEY:'test-only',MAIL_FROM:'WUGONG <noreply@example.test>',MAIL_ORIGIN:'https://shop.test',ASSETS:{fetch:async()=>new Response('asset')}};
 t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');mail.push(JSON.parse(options.body));return Response.json({id:'test-mail'});});
 const call=async(path,method='GET',data,token='')=>{const r=await worker.fetch(new Request('https://shop.test'+path,{method,headers:{Origin:'https://shop.test','Content-Type':'application/json',Cookie:token},body:data===undefined?undefined:JSON.stringify(data)}),env);return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const payload={email:'email-a@example.test',password:'original long test password',name:'郵件測試甲',birthday:'1990-01-01',country:'TW'};
 const a=await call('/api/member/register','POST',payload);assert.equal(a.status,200);assert.equal(a.data.verificationSent,true);assert.equal(a.data.member.emailVerified,false);
 const token=()=>new URLSearchParams(mail.at(-1).text.match(/https:\/\/shop.test\/member#([^\s]+)/)[1]).get('token');
 const verifyA=token();assert.ok(!JSON.stringify(a.data).includes(verifyA));assert.ok(!JSON.stringify(DB.sql.prepare('SELECT * FROM member_email_tokens').all()).includes(verifyA));
 const b=await call('/api/member/register','POST',{...payload,email:'email-b@example.test'});assert.equal(b.status,200);
 assert.equal((await call('/api/member/verify-email','POST',{token:verifyA},b.cookie)).status,200);
 assert.equal((await call('/api/member','GET',undefined,a.cookie)).data.member.emailVerified,true);
 assert.equal((await call('/api/member','GET',undefined,b.cookie)).data.member.emailVerified,false);
 assert.equal((await call('/api/member/verify-email','POST',{token:verifyA})).status,400);
 const forgot=await call('/api/member/forgot-password','POST',{email:payload.email});const reset=token();
 const absent=await call('/api/member/forgot-password','POST',{email:'absent@example.test'});assert.deepEqual(forgot.data,absent.data);
 assert.equal((await call('/api/member/verify-email','POST',{token:reset})).status,400);
 const newPassword='replacement long test password';
 assert.equal((await call('/api/member/reset-password','POST',{token:reset,password:newPassword})).status,200);
 assert.equal((await call('/api/member/reset-password','POST',{token:reset,password:'second replacement long password'})).status,400);
 assert.equal((await call('/api/member','GET',undefined,a.cookie)).data.member,null);
 assert.equal((await call('/api/member/login','POST',{email:payload.email,password:payload.password})).status,401);
 const login=await call('/api/member/login','POST',{email:payload.email,password:newPassword});assert.equal(login.status,200);
 await call('/api/member/forgot-password','POST',{email:payload.email});const expired=token();DB.sql.exec('UPDATE member_email_tokens SET expires_at=0');
 assert.equal((await call('/api/member/reset-password','POST',{token:expired,password:newPassword})).status,400);
 await call('/api/member/forgot-password','POST',{email:payload.email});const invalidated=token();
 assert.equal((await call('/api/member/password','POST',{currentPassword:newPassword,password:'changed again long password'},login.cookie)).status,200);
 assert.equal((await call('/api/member/reset-password','POST',{token:invalidated,password:newPassword})).status,400);
 assert.equal((await call('/api/member/resend-verification','POST',{},b.cookie)).status,200);const verifyExpired=token();DB.sql.exec('UPDATE member_email_tokens SET expires_at=0');
 assert.equal((await call('/api/member/verify-email','POST',{token:verifyExpired})).status,400);
 env.MAIL_ORIGIN='https://different.test';
 assert.equal((await call('/api/member/forgot-password','POST',{email:payload.email})).status,503);
 assert.equal((await call('/api/member')).data.emailAvailable,false);
 DB.sql.close();
});

test('mail failures preserve registered account and never mark unsent mail as sent',async t=>{
 const DB=database();const env={DB,APP_ENV:'staging',RESEND_API_KEY:'test-only',MAIL_FROM:'noreply@example.test',MAIL_ORIGIN:'https://shop.test'};
 t.mock.method(globalThis,'fetch',async()=>Response.json({error:'simulated'},{status:503}));
 const r=await worker.fetch(new Request('https://shop.test/api/member/register',{method:'POST',headers:{Origin:'https://shop.test','Content-Type':'application/json'},body:JSON.stringify({email:'failure@example.test',password:'long test password for failure',name:'測試',birthday:'1990-01-01',country:'TW'})}),env);
 assert.equal(r.status,200);assert.equal((await r.json()).verificationSent,false);assert.equal(DB.sql.prepare('SELECT count(*) n FROM member_email_tokens').get().n,0);assert.equal(DB.sql.prepare('SELECT count(*) n FROM members').get().n,1);DB.sql.close();
});
