import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {orderConversation,notificationPayload,drainNotifications,notificationStatus} from './order-notifications.js';
function setup(){const sql=new DatabaseSync(':memory:');const DB={prepare(q){let p=[];return{bind(...v){p=v;return this;},async first(){return sql.prepare(q).get(...p)||null;},async all(){return{results:sql.prepare(q).all(...p)};},async run(){return{meta:{changes:sql.prepare(q).run(...p).changes}};}};},async batch(statements){sql.exec('BEGIN');try{const r=[];for(const s of statements)r.push(s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
sql.exec(`CREATE TABLE orders(order_number TEXT PRIMARY KEY,email TEXT,note TEXT,created_at TEXT);CREATE TABLE member_orders(order_number TEXT,member_id TEXT);CREATE TABLE admin_audit(id TEXT PRIMARY KEY,member_id TEXT,action TEXT,order_number TEXT,previous_status TEXT,next_status TEXT,created_at TEXT);INSERT INTO orders VALUES ('A','buyer@example.test','請小心包裝\n配送運費：NT$60','2026-10-06T00:00:00Z');INSERT INTO member_orders VALUES ('A','owner');INSERT INTO orders VALUES ('B','other@example.test','','2026-10-06T00:00:00Z');INSERT INTO member_orders VALUES ('B','other');`);
const env={DB,RESEND_API_KEY:'fake',MAIL_FROM:'shop@example.test',MAIL_ORIGIN:'https://shop.test'};
const call=(method,data={},admin=false,order='A',actor='owner',before='')=>{const url=new URL('https://shop.test/api/'+(admin?'admin':'member')+'/order-messages?order='+order+before);return orderConversation(new Request(url,{method,...(method==='GET'?{}:{body:JSON.stringify(data)})}),env,url,{id:actor},admin,r=>r.json());};return{sql,env,call};}
test('owner-only append, initial import, no buyer deletion, idempotent queue and reply recipient',async()=>{const {sql,env,call}=setup();let d=await call('GET');assert.equal(d.messages[0].body,'請小心包裝');assert.equal((await call('GET')).messages.length,1);await assert.rejects(call('GET',{},false,'B'),e=>e.status===404);await assert.rejects(call('DELETE',{id:d.messages[0].seq}),e=>e.status===403);await assert.rejects(call('POST',{text:'   ',key:crypto.randomUUID()}),e=>e.status===400);
const message={text:'<script>alert(1)</script>\n請確認尖型',key:crypto.randomUUID()};await Promise.all([call('POST',message),call('POST',message)]);assert.equal((await call('GET')).messages.length,2);assert.equal(sql.prepare('SELECT count(*) n FROM order_notifications').get().n,1);assert.deepEqual(JSON.parse(sql.prepare('SELECT payload FROM order_notifications').get().payload).to,['wugong.pen@gmail.com']);await assert.rejects(call('POST',{...message,text:'different'}),e=>e.status===409);
await call('POST',{text:'已確認，謝謝！',key:crypto.randomUUID()},true);let mail=[];await drainNotifications(env,async(u,o)=>{mail.push(JSON.parse(o.body));return Response.json({id:'mail-'+mail.length});});assert.equal(mail.length,2);assert.equal(mail[1].to[0],'buyer@example.test');assert.match(mail[1].text,/已確認/);assert.equal(mail[0].html,undefined);const status=await notificationStatus(env,'A');assert.equal(status.notifications.length,2);assert.ok(status.notifications.every(n=>n.kind==='order_message'));sql.close();});
test('admin deletion redacts original, cancels unsent mail, preserves tombstone and audit',async()=>{const {sql,env,call}=setup();await call('POST',{text:'請改時間',key:crypto.randomUUID()});let d=await call('GET');await call('DELETE',{id:d.messages[1].seq},true);await call('DELETE',{id:d.messages[0].seq},true);d=await call('GET');assert.equal(d.messages.length,2);assert.ok(d.messages.every(m=>m.deleted_at&&m.body===''));assert.equal(sql.prepare('SELECT note FROM orders WHERE order_number=?').get('A').note,'\n配送運費：NT$60');assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'cancelled');assert.equal(sql.prepare('SELECT count(*) n FROM admin_audit').get().n,2);await drainNotifications(env,()=>{throw Error('must not send');});sql.close();});
test('conversation paging retains chronological messages and admin new-order email includes checkout note',async()=>{const {sql,env,call}=setup();await call('GET');for(let i=0;i<55;i++)await call('POST',{text:'訊息 '+i,key:crypto.randomUUID()});const last=await call('GET');assert.equal(last.messages.length,50);assert.equal(last.hasMore,true);const first=await call('GET',{},false,'A','owner','&before='+last.messages[0].seq);assert.equal(first.messages.length,6);assert.equal(first.hasMore,false);assert.ok(first.messages.at(-1).seq<last.messages[0].seq);const payload=notificationPayload(env,{order_number:'A',created_at:'now',email:'buyer@example.test',country:'TW',items:[],total:100,note:'請確認筆尖',payment:'bank'});assert.match(payload.text,/請確認筆尖/);sql.close();});
