import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {notificationSchema,notificationStatement,notificationPayload,drainNotifications,notificationStatus,queueTestNotification} from './order-notifications.js';
function setup(){const sql=new DatabaseSync(':memory:');const DB={prepare(q){let p=[];return{bind(...v){p=v;return this;},async first(){return sql.prepare(q).get(...p)||null;},async all(){return{results:sql.prepare(q).all(...p)};},async run(){return{meta:{changes:sql.prepare(q).run(...p).changes}};}};}};return{sql,env:{DB,APP_ENV:'staging',RESEND_API_KEY:'fake-test-only',MAIL_FROM:'WUGONG <test@example.test>',MAIL_ORIGIN:'https://shop.example.test'}};}
const order={order_number:'WG-NOTIFY-1',created_at:'2026-09-25T00:00:00.000Z',email:'buyer@example.test',country:'JP',items:[{product:'<img src=x>',quantity:1}],total:10500,payment:'paypal_invoice'};
test('notification is a fixed recipient plain-text order snapshot with authenticated link',()=>{const {env}=setup(),p=notificationPayload(env,order);assert.deepEqual(p.to,['wugong.pen@gmail.com']);assert.equal(p.html,undefined);assert.match(p.text,/10500/);assert.match(p.text,/不代表買家已付款/);assert.match(p.text,/admin-order-detail.html\?order=WG-NOTIFY-1/);assert.match(p.subject,/測試訂單/);});
test('duplicate queue records and concurrent drain cannot send two requests',async()=>{const {sql,env}=setup();await notificationSchema(env);await notificationStatement(env,order).run();await assert.rejects(notificationStatement(env,order).run());let calls=0;const sender=async()=>{calls++;await new Promise(r=>setTimeout(r,10));return Response.json({id:'mail-1'});};await Promise.all([drainNotifications(env,sender),drainNotifications(env,sender)]);await drainNotifications(env,sender);assert.equal(calls,1);assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'sent');sql.close();});
test('uncertain send retries use identical payload and key, then stop after acceptance',async()=>{const {sql,env}=setup();await notificationSchema(env);await notificationStatement(env,order).run();const requests=[];await drainNotifications(env,async(u,o)=>{requests.push(o);throw Error('connection lost');});assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'queued');sql.exec('UPDATE order_notifications SET next_attempt=0');await drainNotifications({...env,MAIL_FROM:'changed@example.test'},async(u,o)=>{requests.push(o);return Response.json({id:'mail-2'});});assert.equal(requests[0].body,requests[1].body);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.equal(sql.prepare('SELECT attempts FROM order_notifications').get().attempts,2);sql.close();});
test('missing configuration keeps order notification queued without sending',async()=>{const {sql,env}=setup();delete env.RESEND_API_KEY;await notificationSchema(env);await notificationStatement(env,order).run();await drainNotifications(env,()=>{throw Error('must not send');});const d=await notificationStatus(env);assert.equal(d.configured,false);assert.equal(d.notifications[0].attempts,0);sql.close();});
test('uncertain messages older than deduplication window require manual attention',async()=>{const {sql,env}=setup();await notificationSchema(env);await notificationStatement(env,order).run();sql.prepare('UPDATE order_notifications SET first_attempt=?,attempts=1').run(Date.now()-24*3600000);await drainNotifications(env,()=>{throw Error('must not send');});assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'attention');sql.close();});
test('test notification sends no customer data or real order',async()=>{const {sql,env}=setup();await queueTestNotification(env);const row=sql.prepare('SELECT * FROM order_notifications').get();assert.equal(row.order_number,null);assert.match(JSON.parse(row.payload).text,/不是買家訂單/);sql.close();});
