import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {buyerEmailPreviews,memberEmailPayload,CARE_DELAY_MS,careNotificationPayload,careNotificationStatements,validateFactoryDate,buyerNotificationPayload,buyerNotificationStatement,notificationSchema,notificationStatement,notificationPayload,drainNotifications,notificationStatus,queueTestNotification} from './order-notifications.js';
function setup(){const sql=new DatabaseSync(':memory:');const DB={prepare(q){let p=[];return{bind(...v){p=v;return this;},async first(){return sql.prepare(q).get(...p)||null;},async all(){return{results:sql.prepare(q).all(...p)};},async run(){return{meta:{changes:sql.prepare(q).run(...p).changes}};}};}};return{sql,env:{DB,APP_ENV:'staging',RESEND_API_KEY:'fake-test-only',MAIL_FROM:'WUGONG <test@example.test>',MAIL_ORIGIN:'https://shop.example.test'}};}
const order={order_number:'WG-NOTIFY-1',created_at:'2026-09-25T00:00:00.000Z',email:'buyer@example.test',country:'JP',items:[{product:'<img src=x>',quantity:1}],total:10500,payment:'paypal_invoice'};
test('notification is a fixed recipient plain-text order snapshot with authenticated link',()=>{const {env}=setup(),p=notificationPayload(env,order);assert.deepEqual(p.to,['wugong.pen@gmail.com']);assert.equal(p.html,undefined);assert.match(p.text,/10500/);assert.match(p.text,/不代表買家已付款/);assert.match(p.text,/admin-order-detail.html\?order=WG-NOTIFY-1/);assert.match(p.subject,/測試訂單/);});
test('duplicate queue records and concurrent drain cannot send two requests',async()=>{const {sql,env}=setup();await notificationSchema(env);await notificationStatement(env,order).run();await assert.rejects(notificationStatement(env,order).run());let calls=0;const sender=async()=>{calls++;await new Promise(r=>setTimeout(r,10));return Response.json({id:'mail-1'});};await Promise.all([drainNotifications(env,sender),drainNotifications(env,sender)]);await drainNotifications(env,sender);assert.equal(calls,1);assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'sent');sql.close();});
test('uncertain send retries use identical payload and key, then stop after acceptance',async()=>{const {sql,env}=setup();await notificationSchema(env);await notificationStatement(env,order).run();const requests=[];await drainNotifications(env,async(u,o)=>{requests.push(o);throw Error('connection lost');});assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'queued');sql.exec('UPDATE order_notifications SET next_attempt=0');await drainNotifications({...env,MAIL_FROM:'changed@example.test'},async(u,o)=>{requests.push(o);return Response.json({id:'mail-2'});});assert.equal(requests[0].body,requests[1].body);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.equal(sql.prepare('SELECT attempts FROM order_notifications').get().attempts,2);sql.close();});
test('missing configuration keeps order notification queued without sending',async()=>{const {sql,env}=setup();delete env.RESEND_API_KEY;await notificationSchema(env);await notificationStatement(env,order).run();await drainNotifications(env,()=>{throw Error('must not send');});const d=await notificationStatus(env);assert.equal(d.configured,false);assert.equal(d.notifications[0].attempts,0);sql.close();});
test('uncertain messages older than deduplication window require manual attention',async()=>{const {sql,env}=setup();await notificationSchema(env);await notificationStatement(env,order).run();sql.prepare('UPDATE order_notifications SET first_attempt=?,attempts=1').run(Date.now()-24*3600000);await drainNotifications(env,()=>{throw Error('must not send');});assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'attention');sql.close();});
test('test notification sends no customer data or real order',async()=>{const {sql,env}=setup();await queueTestNotification(env);const row=sql.prepare('SELECT * FROM order_notifications').get();assert.equal(row.order_number,null);assert.match(JSON.parse(row.payload).text,/不是買家訂單/);sql.close();});

test('buyer confirmations are bilingual, distinguish invoice from payment, and omit private notes',()=>{
 const {env,sql}=setup();const p=buyerNotificationPayload(env,{...order,note:'SECRET'},'confirmed');
 assert.deepEqual(p.to,[order.email]);assert.equal(p.reply_to,'wugong.pen@gmail.com');assert.match(p.text,/separate PayPal invoice/);assert.match(p.text,/本信不是付款帳單/);assert.ok(!/測試|TEST NOTICE|Do not pay/.test(p.subject+p.text));assert.ok(!p.text.includes('SECRET'));assert.equal(p.html,undefined);
 const bank=buyerNotificationPayload({...env,APP_ENV:'production'},{...order,payment:'bank'},'confirmed');assert.match(bank.text,/does not confirm payment/);assert.ok(!bank.subject.includes('TEST'));
 const ship=buyerNotificationPayload(env,order,'shipped',{carrier:'郵局',tracking:'TRACK-1',admin_note:'SECRET'});assert.match(ship.text,/TRACK-1/);assert.match(ship.text,/Carrier: 郵局/);assert.ok(!ship.text.includes('SECRET'));sql.close();
});
test('buyer events coexist with administrator notification and retry without changing their payload',async()=>{
 const {env,sql}=setup();sql.exec('CREATE TABLE admin_audit(id TEXT PRIMARY KEY)');await notificationSchema(env);await notificationStatement(env,order).run();await buyerNotificationStatement(env,order,'confirmed').run();
 await buyerNotificationStatement(env,order,'shipped','missing',{tracking:'TRACK'}).run();assert.equal(sql.prepare('SELECT count(*) n FROM order_notifications').get().n,2);
 sql.exec("INSERT INTO admin_audit VALUES ('ship')");await buyerNotificationStatement(env,order,'shipped','ship',{tracking:'TRACK'}).run();await assert.rejects(buyerNotificationStatement(env,order,'confirmed').run());
 const d=await notificationStatus(env,order.order_number);assert.equal(d.notifications.length,3);assert.deepEqual(new Set(d.notifications.map(r=>r.kind)),new Set(['admin','buyer_confirmed','buyer_shipped']));
 const requests=[];await drainNotifications(env,async(u,o)=>{requests.push(o);throw Error('timeout');});sql.exec('UPDATE order_notifications SET next_attempt=0');await drainNotifications(env,async(u,o)=>{requests.push(o);return Response.json({id:'receipt'});});
 for(const id of ['new-order/','buyer-confirmed/','buyer-shipped/']){const sent=requests.filter(r=>r.headers['Idempotency-Key']===id+order.order_number);assert.equal(sent.length,2);assert.equal(sent[0].body,sent[1].body);}sql.close();
});

test('factory dates reject invalid calendar dates and shipment email states one-year warranty',()=>{for(const d of ['', '2026-02-30','2100-01-01','bad'])assert.throws(()=>validateFactoryDate(d));assert.equal(validateFactoryDate('2024-02-29'),'2024-02-29');const {env,sql}=setup();const p=buyerNotificationPayload(env,order,'shipped',{factory_date:'2026-01-01'});assert.match(p.text,/Factory date: 2026-01-01/);assert.match(p.text,/One year from the factory date/);sql.close();});

test('care email is bilingual, replyable and does not assume parcel arrival or promise a one-time service',()=>{
 const {env,sql}=setup(),p=careNotificationPayload(env,order);assert.deepEqual(p.to,[order.email]);assert.equal(p.reply_to,'wugong.pen@gmail.com');for(const text of ['刮紙','出墨不順','尚未收到商品','scratchy','has not arrived','one-year warranty'])assert.ok(p.text.includes(text),text);assert.ok(!p.text.includes('一次'));assert.equal(p.html,undefined);sql.close();
});
test('care is scheduled atomically only for pen orders, waits five days and sends once after completion',async t=>{
 const {env,sql}=setup();sql.exec("CREATE TABLE admin_audit(id TEXT PRIMARY KEY);CREATE TABLE orders(order_number TEXT PRIMARY KEY,status TEXT);INSERT INTO admin_audit VALUES ('ship')");await notificationSchema(env);
 const pen={...order,items:[{product:'Pen',category:'pen',quantity:1}]};sql.prepare('INSERT INTO orders VALUES (?,?)').run(order.order_number,'completed');
 assert.equal(careNotificationStatements(env,{...order,items:[{category:'ink'}]},'ship').length,0);
 await careNotificationStatements(env,pen,'missing')[0].run();assert.equal(sql.prepare('SELECT count(*) n FROM order_notifications').get().n,0);
 const start=Date.now();t.mock.method(Date,'now',()=>start);await careNotificationStatements(env,pen,'ship')[0].run();await assert.rejects(careNotificationStatements(env,pen,'ship')[0].run());
 const row=sql.prepare('SELECT * FROM order_notifications').get();assert.equal(row.next_attempt,start+CARE_DELAY_MS);assert.equal(row.first_attempt,null);
 const state=await notificationStatus(env,order.order_number);assert.equal(state.notifications[0].kind,'buyer_care');assert.equal(state.notifications[0].next_attempt,start+CARE_DELAY_MS);
 let calls=0;const send=async()=>{calls++;return Response.json({id:'care-receipt'});};
 await drainNotifications(env,send);assert.equal(calls,0);t.mock.method(Date,'now',()=>start+CARE_DELAY_MS-1);await drainNotifications(env,send);assert.equal(calls,0);
 t.mock.method(Date,'now',()=>start+CARE_DELAY_MS);await Promise.all([drainNotifications(env,send),drainNotifications(env,send)]);await drainNotifications(env,send);assert.equal(calls,1);assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'sent');sql.close();
});
test('care suppresses cancelled orders and failed attempts retain the same payload and key',async()=>{
 const {env,sql}=setup();sql.exec("CREATE TABLE admin_audit(id TEXT PRIMARY KEY);CREATE TABLE orders(order_number TEXT PRIMARY KEY,status TEXT);INSERT INTO admin_audit VALUES ('ship')");await notificationSchema(env);
 const pen={...order,items:[{category:'pen'}]};sql.prepare('INSERT INTO orders VALUES (?,?)').run(order.order_number,'cancelled');await careNotificationStatements(env,pen,'ship')[0].run();sql.exec('UPDATE order_notifications SET next_attempt=0');await drainNotifications(env,()=>{throw Error('must not send');});assert.equal(sql.prepare('SELECT state FROM order_notifications').get().state,'cancelled');
 const other={...pen,order_number:'SECOND'};sql.prepare('INSERT INTO orders VALUES (?,?)').run('SECOND','shipped');await careNotificationStatements(env,other,'ship')[0].run();sql.exec('UPDATE order_notifications SET next_attempt=0');const requests=[];
 await drainNotifications(env,async(u,o)=>{requests.push(o);throw Error('connection lost');});sql.exec('UPDATE order_notifications SET next_attempt=0');await drainNotifications(env,async(u,o)=>{requests.push(o);return Response.json({id:'care-retry'});});assert.equal(requests.length,2);assert.equal(requests[0].body,requests[1].body);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);sql.close();
});

test('all six buyer mail previews use formal bilingual templates without test language',()=>{const {env,sql}=setup();const mails=buyerEmailPreviews(env,'owner@example.test');assert.equal(mails.length,6);for(const p of mails){assert.deepEqual(p.to,['owner@example.test']);assert.ok(!/測試|TEST NOTICE|網站尚未開放正式收款/.test(p.subject+p.text));assert.match(p.subject,/內容預覽/);}for(const purpose of ['verify','reset']){const p=memberEmailPayload(env,'buyer@example.test',purpose,'https://shop.example/member#secure');assert.ok(!/測試/.test(p.subject));assert.match(p.text,/Do not share/);}sql.close();});

test('legacy unattempted buyer notices lose test copy; uncertain old sends stop for review',async()=>{
 const {env,sql}=setup();await notificationSchema(env);
 const legacy={from:env.MAIL_FROM,to:[order.email],subject:'【測試 / TEST】WUGONG 出貨通知',text:'【測試通知】舊版說明\nTEST NOTICE: Old notice\n\n正式內容'};
 for(const [id,attempts]of [['buyer-shipped/NEW',0],['buyer-shipped/OLD',1]])sql.prepare('INSERT INTO order_notifications(id,payload,created_at,attempts) VALUES (?,?,?,?)').run(id,JSON.stringify(legacy),new Date().toISOString(),attempts);
 const sent=[];await drainNotifications(env,async(u,o)=>{sent.push(JSON.parse(o.body));return Response.json({id:'formal'});});assert.equal(sent.length,1);assert.equal(sent[0].text,'正式內容');assert.ok(!sent[0].subject.includes('測試'));assert.equal(sql.prepare("SELECT state FROM order_notifications WHERE id='buyer-shipped/OLD'").get().state,'attention');sql.close();
});
