import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {checkMac} from './ecpay.js';
import {shippingQuote,shippingStatements,shippingSchema} from './shipping.js';
import {firstGiftQuote,firstGiftStatements,firstGiftForOrder} from './first-purchase.js';
const require=createRequire(import.meta.url);
const {Miniflare,convertV4MiniflareOptions}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler')]}));
test('Cloudflare runtime supports password hashing and D1 membership',async()=>{
 const mf=new Miniflare(convertV4MiniflareOptions({modules:[{type:'ESModule',path:fileURLToPath(new URL('./worker.js',import.meta.url)),contents:readFileSync(new URL('./worker.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./first-purchase.js',import.meta.url)),contents:readFileSync(new URL('./first-purchase.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./countries.js',import.meta.url)),contents:readFileSync(new URL('./countries.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./ecpay.js',import.meta.url)),contents:readFileSync(new URL('./ecpay.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./payments.js',import.meta.url)),contents:readFileSync(new URL('./payments.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./inventory.js',import.meta.url)),contents:readFileSync(new URL('./inventory.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./commerce.js',import.meta.url)),contents:readFileSync(new URL('./commerce.js',import.meta.url),'utf8')},{type:'ESModule',path:fileURLToPath(new URL('./modules.js',import.meta.url)),contents:readFileSync(new URL('./modules.js',import.meta.url),'utf8')},...['shipping.js','homepage-store.js','homepage-config.js','content-store.js','content-model.js'].map(f=>({type:'ESModule',path:fileURLToPath(new URL(f,import.meta.url)),contents:readFileSync(new URL(f,import.meta.url),'utf8')}))],compatibilityDate:'2026-09-07',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{APP_ENV:'staging',PAYMENT_ORIGIN:'https://wugong-test.wugong-pen.workers.dev',BANK_TEST_CONFIG:JSON.stringify({bank:'測試銀行',code:'TEST',branch:'測試分行',holder:'測試戶名',account:'TEST-NOT-A-REAL-ACCOUNT',days:3})}}));
 try{
  const db=await mf.getD1Database('DB');
  const schema=readFileSync(new URL('./schema-members.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'');
  for(const statement of schema.split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-admin.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  const response=await mf.dispatchFetch('https://shop.test/api/member/register',{method:'POST',headers:{Origin:'https://shop.test','Content-Type':'application/json'},body:JSON.stringify({email:'runtime@example.test',password:'runtime test password is long',name:'測試會員',birthday:'1990-01-01',country:'TW'})});
  assert.equal(response.status,200,await response.clone().text());const result=await response.json();assert.equal(response.status,200,JSON.stringify(result));assert.equal(result.member.name,'測試會員');
  const cookie=response.headers.get('set-cookie').split(';')[0];
  const me=await mf.dispatchFetch('https://shop.test/api/member',{headers:{Cookie:cookie}});assert.equal((await me.json()).member.email,'runtime@example.test');
  assert.equal((await mf.dispatchFetch('https://shop.test/api/admin/session',{headers:{Cookie:cookie}})).status,403);
  await db.prepare('INSERT INTO admin_members VALUES (?,1,?)').bind(result.member.id,new Date().toISOString()).run();
  const adminLogin=await mf.dispatchFetch('https://shop.test/api/admin/login',{method:'POST',headers:{Origin:'https://shop.test','Content-Type':'application/json'},body:JSON.stringify({email:'runtime@example.test',password:'runtime test password is long'})});
  assert.equal(adminLogin.status,200);const adminCookie=adminLogin.headers.get('set-cookie').split(';')[0];
  assert.equal((await mf.dispatchFetch('https://shop.test/api/admin/session',{headers:{Cookie:adminCookie}})).status,200);
  await db.prepare('CREATE TABLE orders(order_number TEXT PRIMARY KEY,customer_name TEXT,phone TEXT,email TEXT,address TEXT,shipping TEXT,payment TEXT,note TEXT,items TEXT,total INTEGER,status TEXT,created_at TEXT)').run();
  for(const statement of readFileSync(new URL('./schema-payments.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-checkout.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').match(/CREATE TRIGGER[\s\S]*?\nEND;|CREATE (?:TABLE|INDEX)[\s\S]*?;/g))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./seed-inventory-staging.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-commerce.sql',import.meta.url),'utf8').match(/CREATE TRIGGER[\s\S]*?END;|CREATE (?:TABLE|INDEX)[\s\S]*?;/g))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./seed-products.sql',import.meta.url),'utf8').replace(/^--.*$/gm,'').split(';').filter(s=>s.trim()))await db.prepare(statement).run();
  for(const statement of readFileSync(new URL('./schema-modules.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await db.prepare(statement).run();for(const statement of readFileSync(new URL('./schema-categories-gifts.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await db.prepare(statement).run();await db.prepare('UPDATE product_families SET confirmed=1').run();await db.prepare("UPDATE inventory SET available=5 WHERE sku LIKE 'body-%'").run();
 const homeDefault=await (await mf.dispatchFetch('https://shop.test/api/homepage')).json();assert.equal(homeDefault.version,0);
 const homeHeaders={Origin:'https://shop.test','Content-Type':'application/json',Cookie:adminCookie};homeDefault.config.texts.title.text='Runtime homepage';

 const servicePayload={id:result.member.id,member_number:'RUNTIME-001',version:0,warranties:[{product:'測試筆',card:'RUNTIME-CARD-001',start_date:'2026-09-18',end_date:'2027-09-18',order_number:'',note:'現場購買'}]};
 const serviceResponse=await mf.dispatchFetch('https://shop.test/api/admin/member-service',{method:'POST',headers:homeHeaders,body:JSON.stringify(servicePayload)});assert.equal(serviceResponse.status,200,await serviceResponse.clone().text());const serviceData=(await serviceResponse.json()).service;
 const competingService=await Promise.all([1,2].map(()=>mf.dispatchFetch('https://shop.test/api/admin/member-service',{method:'POST',headers:homeHeaders,body:JSON.stringify({id:result.member.id,...serviceData})})));assert.deepEqual(competingService.map(r=>r.status).sort(),[200,409]);
 const memberDetail=await (await mf.dispatchFetch('https://shop.test/api/admin/member?id='+result.member.id,{headers:homeHeaders})).json();assert.equal(memberDetail.service.warranties.length,1);assert.equal(memberDetail.service.version,2);
 const homeSaved=await mf.dispatchFetch('https://shop.test/api/admin/homepage',{method:'POST',headers:homeHeaders,body:JSON.stringify({config:homeDefault.config,version:0})});assert.equal(homeSaved.status,200,await homeSaved.clone().text());assert.equal((await homeSaved.json()).version,1);
 assert.equal((await (await mf.dispatchFetch('https://shop.test/api/homepage')).json()).config.texts.title.text,'Runtime homepage');
 const homeConflict=await mf.dispatchFetch('https://shop.test/api/admin/homepage',{method:'POST',headers:homeHeaders,body:JSON.stringify({config:homeDefault.config,version:0})});assert.equal(homeConflict.status,409);
 const contentEmpty=await mf.dispatchFetch('https://shop.test/api/content');assert.equal(contentEmpty.status,200);assert.deepEqual((await contentEmpty.json()).entries,[]);
 const contentDraft={id:'',version:0,kind:'events',status:'draft',title:'Runtime event',summary:'Event summary',date:'2026-09-16',cover:'',source:'',blocks:[{type:'text',text:'Event details'}]};
 const createContent=await mf.dispatchFetch('https://shop.test/api/admin/content-entry',{method:'POST',headers:homeHeaders,body:JSON.stringify(contentDraft)});assert.equal(createContent.status,200,await createContent.clone().text());const contentEntry=(await createContent.json()).entry;
 assert.equal((await mf.dispatchFetch('https://shop.test/api/content-entry?id='+contentEntry.id)).status,404);
 const competingContent=await Promise.all([1,2].map(()=>mf.dispatchFetch('https://shop.test/api/admin/content-entry',{method:'POST',headers:homeHeaders,body:JSON.stringify({...contentEntry,status:'published'})})));assert.deepEqual(competingContent.map(r=>r.status).sort(),[200,409]);
 assert.equal((await (await mf.dispatchFetch('https://shop.test/api/content?kind=events')).json()).entries[0].title,'Runtime event');
 const payload={customer:{name:'測試',phone:'0900000000',address:'測試地址',country:'TW'},items:[{id:'pojun-單尖',nib:'單尖',price:1,quantity:1}],expectedTotal:25000,payment:'bank',shipping:'宅配'};
  const orderResponse=await mf.dispatchFetch('https://shop.test/api/order',{method:'POST',headers:{Origin:'https://shop.test','Content-Type':'application/json',Cookie:cookie,'Idempotency-Key':'runtime-payment-0001'},body:JSON.stringify(payload)});
  const order=await orderResponse.json();assert.equal(orderResponse.status,200,JSON.stringify(order));
  const params={MerchantID:'3002607',MerchantTradeNo:order.orderNumber,TradeAmt:'25000',RtnCode:'1',SimulatePaid:'0',TradeNo:'runtime123',PaymentType:'Credit_CreditCard'};
  const notice=await mf.dispatchFetch('https://shop.test/api/payments/ecpay/notify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...params,CheckMacValue:checkMac(params)}).toString()});
  assert.equal(notice.status,503);assert.equal((await db.prepare('SELECT status FROM orders WHERE order_number=?').bind(order.orderNumber).first()).status,'pending');
  assert.equal((await db.prepare("SELECT available FROM inventory WHERE sku='body-product-pojun'").first()).available,4);
  const headers={Origin:'https://shop.test','Content-Type':'application/json',Cookie:cookie,'Idempotency-Key':'runtime-bank-00001'};
  const bankOrder=await (await mf.dispatchFetch('https://shop.test/api/order',{method:'POST',headers,body:JSON.stringify({...payload,payment:'bank'})})).json();assert.equal(bankOrder.success,true);
  const post=async(path,data,h=headers)=>{const r=await mf.dispatchFetch('https://shop.test'+path,{method:'POST',headers:h,body:JSON.stringify(data)});return {status:r.status,...await r.json()};};
  const bank=await post('/api/payments/start',{orderNumber:bankOrder.orderNumber});assert.equal(bank.success,true);assert.equal(bank.bank.days,3);
  assert.equal((await post('/api/payments/start',{orderNumber:bankOrder.orderNumber})).dueAt,bank.dueAt);
  const report=await post('/api/payments/bank/report',{orderNumber:bankOrder.orderNumber,last5:'12345',date:new Date(Date.now()+8*3600000).toISOString().slice(0,10)});assert.equal(report.success,true,JSON.stringify(report));
  assert.equal((await db.prepare('SELECT status FROM orders WHERE order_number=?').bind(bankOrder.orderNumber).first()).status,'pending');
  assert.equal((await post('/api/payments/start',{orderNumber:bankOrder.orderNumber},{Origin:'https://shop.test','Content-Type':'application/json'})).status,401);
  await db.prepare("UPDATE payment_attempts SET due_at='2000-01-01T00:00:00.000Z' WHERE order_number=?").bind(bankOrder.orderNumber).run();
  assert.equal((await post('/api/payments/bank/report',{orderNumber:bankOrder.orderNumber,last5:'12345',date:new Date(Date.now()+8*3600000).toISOString().slice(0,10)})).status,409);
  const competing=await Promise.all(Array.from({length:8},(_,i)=>post('/api/order',{...payload,payment:'bank'},{...headers,'Idempotency-Key':'concurrent-stock-'+i})));
  assert.equal(competing.filter(r=>r.status===200).length,3,JSON.stringify(competing));
  assert.equal(competing.filter(r=>r.status===409).length,5,JSON.stringify(competing));
  assert.equal((await db.prepare("SELECT available FROM inventory WHERE sku='body-product-pojun'").first()).available,0);
  assert.equal((await db.prepare('SELECT count(*) n FROM orders').first()).n,5);
  const repeated=await Promise.all(Array.from({length:8},()=>post('/api/order',{...payload,payment:'bank',items:[{id:'product-fuji',nib:'WUGONG 筆尖',quantity:1}],expectedTotal:120000},{...headers,'Idempotency-Key':'concurrent-identical-request'})));
  assert.ok(repeated.every(r=>r.status===200),JSON.stringify(repeated));
  assert.equal(new Set(repeated.map(r=>r.orderNumber)).size,1);
  assert.equal((await db.prepare("SELECT available FROM inventory WHERE sku='body-product-fuji'").first()).available,4);
  assert.equal((await db.prepare('SELECT count(*) n FROM orders').first()).n,6);
  const adminHeaders={Origin:'https://shop.test','Content-Type':'application/json',Cookie:adminCookie};
  const edits=await Promise.all(Array.from({length:5},()=>post('/api/admin/family',{family:'product-fuji',version:1,threshold:2,expected:4,delta:1,reason:'concurrent adjustment'},adminHeaders)));
  assert.equal(edits.filter(r=>r.status===200).length,1,JSON.stringify(edits));assert.equal(edits.filter(r=>r.status===409).length,4);
  assert.equal((await db.prepare("SELECT available FROM inventory WHERE sku='body-product-fuji'").first()).available,5);
  assert.equal((await db.prepare("SELECT count(*) n FROM commerce_audit WHERE action='family.stock'").first()).n,1);
  const coupon={code:'RUNTIME',kind:'fixed',amount:100,minimum:100,maximum:100,scope:'all',target:'',starts:new Date(Date.now()-60000).toISOString(),ends:new Date(Date.now()+86400000).toISOString(),quota:1,active:1,version:0};
  assert.equal((await post('/api/admin/coupon',coupon,adminHeaders)).status,200);
  const discounted={...payload,items:[{id:'product-egypt',nib:'WUGONG 筆尖',quantity:1}],coupon:'RUNTIME',expectedTotal:149900};
  const quote=await post('/api/checkout/quote',{items:discounted.items,coupon:'RUNTIME'});assert.equal(quote.total,149900);assert.equal(quote.discount,100);
  const couponOrders=await Promise.all(Array.from({length:5},(_,i)=>post('/api/order',discounted,{...headers,'Idempotency-Key':'coupon-concurrent-'+i})));
  assert.equal(couponOrders.filter(r=>r.status===200).length,1,JSON.stringify(couponOrders));assert.equal(couponOrders.filter(r=>r.status===409).length,4,JSON.stringify(couponOrders));
  assert.equal((await db.prepare("SELECT available FROM inventory WHERE sku='body-product-egypt'").first()).available,4);
  assert.equal((await db.prepare('SELECT count(*) n FROM promotion_claims').first()).n,1);
  const png=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6v1UAAAAASUVORK5CYII=','base64'));
  const uploaded=await mf.dispatchFetch('https://shop.test/api/admin/images',{method:'POST',headers:{...adminHeaders,'Content-Type':'image/png'},body:png});assert.equal(uploaded.status,200);const uploadedData=await uploaded.json();const media=await mf.dispatchFetch('https://shop.test'+uploadedData.url);assert.deepEqual(new Uint8Array(await media.arrayBuffer()),png);
  // D1 serializes competing gift reservations, including different accounts sharing a phone.
  const giftEnv={DB:db};
  const gift=await firstGiftQuote(giftEnv,[{category:'pen'}],'phone-runtime-a','TW','','0912345678');assert.ok(gift);
  const giftBatch=(number,member)=>[
   db.prepare("INSERT INTO orders(order_number,status,phone) VALUES (?,'pending','0912345678')").bind(number),
   ...firstGiftStatements(giftEnv,gift,member,number,'+886912345678')
  ];
  const phoneRace=await Promise.allSettled([db.batch(giftBatch('PHONE-RUNTIME-A','phone-runtime-a')),db.batch(giftBatch('PHONE-RUNTIME-B','phone-runtime-b'))]);
  assert.equal(phoneRace.filter(r=>r.status==='fulfilled').length,1);
  assert.equal((await db.prepare("SELECT count(*) n FROM orders WHERE order_number LIKE 'PHONE-RUNTIME-%'").first()).n,1);
  const held=await db.prepare("SELECT order_number FROM orders WHERE order_number LIKE 'PHONE-RUNTIME-%'").first();
  await db.prepare("UPDATE orders SET status='shipped' WHERE order_number=?").bind(held.order_number).run();
  assert.equal((await firstGiftForOrder(giftEnv,held.order_number)).state,'reserved');
  assert.equal((await post('/api/admin/order/status',{orderNumber:held.order_number,expectedStatus:'shipped',status:'completed'},adminHeaders)).status,200);
  assert.equal((await firstGiftForOrder(giftEnv,held.order_number)).state,'received');
  await db.prepare("UPDATE orders SET status='cancelled' WHERE order_number=?").bind(held.order_number).run();
  assert.equal((await db.prepare('SELECT count(*) n FROM first_purchase_claims WHERE order_number=?').bind(held.order_number).first()).n,0);
  assert.ok(await firstGiftQuote(giftEnv,[{category:'pen'}],'phone-runtime-new','TW','','+886 912345678'));
  await shippingSchema({DB:db});
  await db.prepare("UPDATE shipping_regions SET enabled=1,fee=1600 WHERE country='US'").run();
  const shipping=await shippingQuote({DB:db},{items:[{category:'pen'}],total:1000},'US',true);assert.equal(shipping.total,2600);
  await db.prepare("UPDATE shipping_regions SET version=version+1,fee=1800 WHERE country='US'").run();
  await assert.rejects(()=>db.batch([db.prepare("INSERT INTO orders(order_number,status) VALUES ('STALE-FREIGHT','pending')"),...shippingStatements({DB:db},shipping,'STALE-FREIGHT')]));
  assert.equal(await db.prepare("SELECT 1 FROM orders WHERE order_number='STALE-FREIGHT'").first(),null);
 }finally{await mf.dispose();}
});

