const $=id=>document.getElementById(id),node=(tag,text)=>{const e=document.createElement(tag);e.textContent=text??'';return e;},money=n=>'NT$ '+Number(n).toLocaleString('zh-TW');
const message=s=>{$('store-message').textContent=s;};let page=1,products=[],selected;
async function catalog(params){const r=await fetch('/api/catalog?'+new URLSearchParams(params),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'無法讀取商品');return d;}
if(document.body.dataset.page==='shop'){
 const initial=new URLSearchParams(location.search);$('category').value=initial.get('category')||'';
 async function load(){message('正在讀取商品…');$('products').replaceChildren();$('previous').disabled=$('next').disabled=true;try{const d=await catalog({category:$('category').value,q:$('search').value,page});for(const p of d.products){const card=node('article');card.className='store-card';const link=node('a');link.href='/product.html?sku='+encodeURIComponent(p.sku);if(p.images[0]){const img=node('img');img.src=p.images[0];img.alt=p.name;img.loading='lazy';link.append(img);}link.append(node('h2',p.name));card.append(link,node('p',p.variant),node('p',money(p.price)),node('p',p.available>0?'可訂購':'暫時售完'));$('products').append(card);}$('previous').disabled=page===1;$('next').disabled=!d.hasMore;$('page').textContent='第 '+page+' 頁';message(d.products.length?'':'此分類目前沒有上架商品。');}catch(e){message(e.message);}}
 $('filters').onsubmit=e=>{e.preventDefault();page=1;load();};$('previous').onclick=()=>{page--;load();};$('next').onclick=()=>{page++;load();};await load();
}else{
 function render(){selected=products.find(p=>p.sku===$('variant').value);if(!selected)return;document.title=selected.name+'｜WUGONG';$('product-name').textContent=selected.name;$('product-description').textContent=selected.description;document.getElementById('product-video')?.remove();if(selected.video){const frame=node('iframe');frame.id='product-video';frame.title='商品影片';frame.src='https://www.youtube-nocookie.com/embed/'+selected.video;frame.allowFullscreen=true;frame.style.cssText='width:100%;aspect-ratio:16/9;border:0';$('product-description').after(frame);}$('product-price').textContent=money(selected.price);$('available').textContent=selected.available>0?'可售庫存：'+selected.available+' 件':'此規格暫時售完';$('quantity').max=Math.min(99,selected.available);$('add').disabled=selected.available<1;$('gallery').replaceChildren();for(const src of selected.images){const img=node('img');img.src=src;img.alt=selected.name;$('gallery').append(img);}}
 try{const params=new URLSearchParams(location.search);let d=await catalog(params.has('sku')?{sku:params.get('sku')}:{family:params.get('family')||''});if(!d.products.length)throw Error('此商品已下架或不存在。');const first=d.products[0];products=(await catalog({family:first.family})).products;for(const p of products){const o=node('option',p.variant+' · '+money(p.price));o.value=p.sku;$('variant').append(o);}$('variant').value=first.sku;$('variant').onchange=render;$('product-content').hidden=false;render();}catch(e){message(e.message);}
 $('add').onclick=()=>{try{const quantity=Number($('quantity').value);if(!selected||!Number.isInteger(quantity)||quantity<1||quantity>Math.min(99,selected.available))throw Error('請確認購買數量');const cart=JSON.parse(localStorage.getItem('wugongCart')||'[]');if(!Array.isArray(cart))throw Error('購物車資料無法讀取');const old=cart.find(i=>i.id===selected.sku&&i.nib===selected.variant),total=quantity+(old?.quantity||0);if(total>Math.min(99,selected.available))throw Error('購物車內的數量已超過目前可售庫存');if(old){old.quantity=total;old.price=selected.price;old.product=selected.name;}else cart.push({id:selected.sku,product:selected.name,nib:selected.variant,price:selected.price,quantity,image:selected.images[0]||''});localStorage.setItem('wugongCart',JSON.stringify(cart));message('已加入購物車。');}catch(e){message(e.message);}};
}
